<?php


function recipeChanger_form_alter(&$form, &$form_state, $form_id) {
    //drupal_set_message("Form ID is : " . $form);

    if($form_id ==  'recipe_name_node_form'){

        $form ['options']['#access']=0;
        $form ['author']['#access']=0;
        $form ['revision_information']['#access']=0;
        $form ['menu']['#access']=0;
        $form ['comment_settings']['#access']=0;
        $form ['comment_settings']['comment']['#default_value'] = 1;


        // print '<pre>';
        // print_r($form);
        // print '</pre>';
    }
}
